name: contactx_example
description: "Demonstrates how to use the contactx plugin."

environment:
  sdk: ^3.7.2
  
dependencies:
  flutter:
    sdk: flutter

  contactx:
    path: ../

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
