name: contactx
description: "ContactX is a powerful and fast Flutter plugin designed to fetch contacts directly from the device. Supports both iOS and Android platforms."
version: 0.0.8
homepage: https://github.com/Asif-Faizal/ContactX
repository: https://github.com/Asif-Faizal/ContactX
issue_tracker: https://github.com/Asif-Faizal/ContactX/issues

environment:
  sdk: '>=3.7.2 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.contactx
        pluginClass: ContactxPlugin
      ios:
        pluginClass: ContactxPlugin
